### PR TITLE
stop posting about BLCK i am tired of seeing it

### PR DESCRIPTION
**Pull request by Fl1pNatic**
on tiktok it's just BLCK on discord it's fucking BLCK, I was in a server, right? AND ALL OF THE CHANNELS ARE JUST "Where I can download BLCK"

### CODE REVIEW

**Comment by Deltara3** [comment]
epic pr

**Comment by Megarion** [comment]
> where can i download blck
you cant

**Comment by Deltara3** [comment]
> you cant

i agree but also disagree

**Comment by Megarion** [comment]
> i agree but also disagree

omg how 2 downlaod blck ???? 😱😱🤔🤔🤔

**Comment by Fl1pNatic** [comment]
> > i agree but also disagree
> 
> omg how 2 downlaod blck ???? 😱😱🤔🤔🤔

jump off a cool looking roof

**Comment by Megarion** [comment]
> jump off a cool looking roof

ok thanks be right back 😀

**Comment by smug-dev** [comment]
i approve of this commit

**Review by smug-dev — APPROVED** [review]

**Comment by boehs** [comment]
What is BLCK

**Comment by rVnPower** [comment]
pls give me the download link

**Comment by sertdfyguhi** [comment]
where blck

**Comment by zTags** [comment]
blck pls

**Comment by SpeckyYT** [comment]
wtf is ANMT

**Comment by Fl1pNatic** [comment]
> wtf is ANMT

idk man sum shit

**Comment by camila314** [comment]
moment

**Comment by SpeckyYT** [comment]
sad

**Pull request closed without merging**
