### PR TITLE
Added @path offering an easy FS accessibility

### PR DESCRIPTION
**Pull request by SpeckyYT**
```rs
@path::new("SputPC:/spwn").delete()
```

### CODE REVIEW

**Comment by zTags** [comment]
```rs
$.rmdirall("/");
```

**Comment by SpeckyYT** [comment]
now this PR is in a really good state 😳 it is ready for merge

**Comment by sertdfyguhi** [comment]
bro some checks haven't completeed yet 🤚

**Comment by itsmebombie** [comment]
noo😭😭😭

**Comment by Fl1pNatic** [comment]
ballin

**Comment by SpeckyYT** [comment]
now it's really sex

**Comment by krista-chan** [comment]
Could you possibly expose [fs perms](https://doc.rust-lang.org/std/fs/struct.Permissions.html) and use them to handle errors like trying to access a file SPWN doesn't have permissions to read? Also would be nice to be able to access the permissions at all, possibly `@path::metadata.permissions`?

**Comment by SpeckyYT** [comment]
Sure 👌

**Comment by SpeckyYT** [comment]
should be good now, it checks if the file exists or if it's read-only 👍

**Comment by krista-chan** [comment]
Swag

**Pull request merged**
