### PR TITLE
minifier + escapes

### PR DESCRIPTION
**Pull request by DexterHill0**
- spwn code minifier
- escape characters
    - `\b` escape character
    - `\u{...}` (unicode) escape
- dye std lib for colour printing

### CODE REVIEW

**Comment by camila314** [comment]
minifier built into spwn doesnt seem like something that needs to be done. maybe make it a separate standalone program?

**Comment by DexterHill0** [comment]
> 
> 
> minifier built into spwn doesnt seem like something that needs to be done. maybe make it a separate standalone program?

I mean it uses multiple of the spwn crates which would be annoying to require in a separate program especailly since they're not on cargo (and aren't going to be). And it's not like it interferes with anything; it's basically the opposite of the builtin formatter (which is just commented out).

**Comment by camila314** [comment]
would be much cleaner to make spwn usable as a crate and then import it in another standalone app imo.

**Comment by DexterHill0** [comment]
I mean I'm down to make the minifier and formatter their own thing but that's only possible if spwn is made into a usuable crate.
I can close this pr and open a new one with just dye and the escape characters if that better

**Pull request closed without merging**
