### PR TITLE
readme but better

### PR DESCRIPTION
**Pull request by zTags**
i have no clue why i like making a pr on the readme this much

### CODE REVIEW

**Review by SpeckyYT — CHANGES_REQUESTED** [review]
after headers, there should be two newlines (i.e an empty line after it)

and also `cmd` allow you to click to copy, which `sh` doesn't

**Comment by zTags** [comment]
fuck

**Comment by zTags** [comment]
ok but for me i can copy \`\`\`sh perfectly fine

**Comment by SpeckyYT** [comment]
> ok but for me i can copy ```sh perfectly fine

ah yeah, nvm

**Review by krista-chan — CHANGES_REQUESTED** [review]
Remove the `$` changes, it should only be used when showing terminal output.

**Comment by zTags** [comment]
didnt i already do that

**Comment by krista-chan** [comment]
[no](https://github.com/Spu7Nix/SPWN-language/pull/198/commits/d0b030035919249f4c9d1ff8d7b5bd4dabe89aaa#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R85)

**Comment by krista-chan** [comment]
oops yeah

**Comment by SpeckyYT** [comment]
[yes](https://github.com/Spu7Nix/SPWN-language/pull/198/files)

**Review by krista-chan — APPROVED** [review]

**Comment by SpeckyYT** [comment]
tbh, I would change `sh` to `cmd`, since it isn't a bash script, and I would remove the double newline 🤮

**Comment by zTags** [comment]
where double newline

**Comment by zTags** [comment]
ok nvm

**Comment by SpeckyYT** [comment]
lmao

**Pull request merged**
