### PR TITLE
http requests in spwn maybe?

### PR DESCRIPTION
**Pull request by jas-dzied**
builtin function `http_get` returns encoded response
std library type `@http` wraps around `http_get` and returns a dictionary of `status` (status code, number), `text` (response text, string) and `headers` (response headers, dictionary).
errors in the built in function are (i think0 properly handled
example usage:
```
let response = @http::get("https://httpbin.org/get")
$.print(response.status)
$.print(response.text)
$.print(response.headers)

let headers = {}
headers.set('custom-header", "custom-value")
let response2 = @http::get("https://httpbin.org/get", headers)
$.print(response.status)
$.print(response.text)
$.print(response.headers)
```

### CODE REVIEW

**Comment by sertdfyguhi** [comment]
woah http requests compile time i love it i can finally do a crypto miner on spwn yay i love it yay

**Comment by zTags** [comment]
cool

**Comment by Spu7Nix** [comment]
why not lmao

**Comment by Deltara3** [comment]
discord.spwn soon 😳 😳 😳 😳

**Pull request merged**
