### PR TITLE
Added extend method to trigger functions

### PR DESCRIPTION
**Pull request by SpeckyYT**
`$.extend_trigger_func` is 🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢

`!{}.extend(!{ sussy() })` 😎

### CODE REVIEW

**Comment by zTags** [comment]
ball

**Comment by zTags** [comment]
no ball

**Comment by kr8gz** [comment]
very ball

**Comment by itsmebombie** [comment]
kinda ball

**Comment by SpeckyYT** [comment]
obv it is ball

**Comment by krista-chan** [comment]
why?

**Comment by SpeckyYT** [comment]
> why?

using the built-in `$.extend_trigger_func` is really ugly *and kinda unintuitive (?)*.
by doing `trigger_func.extend(!{ code })` it is easier and less ugly.

**Pull request closed without merging**
