### PR TITLE
Create ASCII.spwn

### PR DESCRIPTION
**Pull request by psbpsbp**
ASCII values to do @string to @number and @number to @string

### CODE REVIEW

**Comment by SpeckyYT** [comment]
why aren't there the `null` `tab` and the other special characters?
it's kinda useless to offset the entire official ascii table and therefore making it unofficial.

**Comment by psbpsbp** [comment]
> why aren't there the `null` `tab` and the other special characters? it's kinda useless to offset the entire official ascii table and therefore making it unofficial.

i'm fixing it i just realized

**Comment by psbpsbp** [comment]
@SpeckyYT Fixed

**Comment by SpeckyYT** [comment]
uhh, special characters aren't strings, but characters

**Comment by psbpsbp** [comment]
> 

okay i didn't find them as characters, i found them now

**Comment by psbpsbp** [comment]
@SpeckyYT Again...

**Comment by psbpsbp** [comment]
@krista-chan  Why did you close it?

**Comment by SpeckyYT** [comment]
tbh, this will never get pulled, but *maybe*, if you implement it in the standard types `@string` and `@number` it *might* get accepted
```rs
@string::to_ascii_codes = (self) -> [@number] {}
@number::to_ascii = (self) -> @string {}
// something like this, but for the actual impl blocks
```

**Comment by krista-chan** [comment]
> @krista-chan Why did you close it?

No changes: [0c3d56e](https://github.com/Spu7Nix/SPWN-language/pull/248/commits/0c3d56e232604678e22746d0d12b53e991de1f9e)

**Comment by SpeckyYT** [comment]
Why was this reopened?

**Comment by krista-chan** [comment]
> Why was this reopened?

i am spuid

**Comment by SpeckyYT** [comment]
> > Why was this reopened?
> 
> i am spuid

Happens to the best of us

**Comment by zTags** [comment]
> i am spuid

hi spuid im tags

**Comment by Unzor** [comment]
true

**Comment by itsmebombie** [comment]
#247

**Comment by 3pm-on-github** [comment]
hi tags im 3pm

**Pull request closed without merging**
