### PR TITLE
added Numeric Separators

### PR DESCRIPTION
**Pull request by SpeckyYT**
```rs
50000000 // 🤮 
50_000_000 // much easier to read
```

### CODE REVIEW

**Comment by Deltara3** [comment]
`_` looks a lot worse than `.` imo

**Comment by sertdfyguhi** [comment]
This pull request should not be merged because:
1. No other programming language supports this
2. Using `_` to separate numbers is a pain to read, I'd rather read `50000000`
3. Separating numbers just looks bad

**Comment by feverdreme** [comment]
> No other programming language implements this

python and javascript implement this

**Comment by feverdreme** [comment]
> Using _ to separate numbers is a pain to read, I'd rather read 50000000 that that

I disagree. Using underscores definitely helps readability with larger numbers. You can't just look at a long chain of digits and determine the magnitude of the number

> Separating numbers just looks bad and makes the number look like a variable name

Sounds like a you problem

**Comment by sertdfyguhi** [comment]
wait python does this?
i did not know

**Comment by sertdfyguhi** [comment]
woah you're so correct <3

**Comment by sertdfyguhi** [comment]
guess im wrong

**Comment by rVnPower** [comment]
i didnt know that

**Comment by FlowVix** [comment]
your mother

**Comment by rVnPower** [comment]
well it does exist in python

**Comment by 7F6** [comment]
LITERALLy just like
`let foo = 5000000 //5,000,000`

**Comment by sertdfyguhi** [comment]
^^^^ THAT

**Comment by Fl1pNatic** [comment]
useless, just like i am

**Comment by 7F6** [comment]
damn bro

**Comment by SpeckyYT** [comment]
> This pull request should not be merged because:
> 1. No other programming language implements this


> Comparison to other languages
Numeric literal separators are widely supported in other programming languages.
>
> Ada: single, between digits
> C#: multiple, between digits
> C++: single, between digits (single quote used as separator)
> Java: multiple, between digits
> JavaScript and TypeScript: single, between digits
> Julia: single, between digits
> Kotlin: multiple, between digits
> Perl: single, between digits
> Python: single, between digits
> Ruby: single, between digits
> Rust: multiple, anywhere
> Swift: multiple, between digits

lmao

**Comment by sertdfyguhi** [comment]
yeas but is useless i already accepted defeat on that one

**Comment by SpeckyYT** [comment]
I don't remember asking 💀

**Comment by SpeckyYT** [comment]
> LITERALLy just like
> `let foo = 5000000 //5,000,000`

If you don't like the `_` standard, we could replace it with `,`.

**Comment by SpeckyYT** [comment]
To reiterate

> This pull request should not be merged because:
> 1. No other programming language implements this

As you saw, there are tons of languages that implemented it (literally ever Rust).

> 2. Using `_` to separate numbers is a pain to read, I'd rather read `50000000` that that

It makes it quite easy to recognize the size of a number quickly.

> 3. Separating numbers just looks bad and makes the number look like a variable name

It's not like you HAVE to use them, you can use them whenever you want since they're optional.

**Comment by zTags** [comment]
> If you don't like the `_` standard, we could replace it with `,` (idk if it's possible tho).

pls

**Comment by 7F6** [comment]
> > LITERALLy just like
> > `let foo = 5000000 //5,000,000`
> 
> If you don't like the `_` standard, we could replace it with `,` (idk if it's possible tho).

no i mean you could just put the value in easier to read format in comment after

**Comment by SpeckyYT** [comment]
> > > LITERALLy just like
> > > `let foo = 5000000 //5,000,000`
> > 
> > If you don't like the `_` standard, we could replace it with `,` (idk if it's possible tho).
> 
> no i mean you could just put the value in easier to read format in comment after

I hate code duplication tbh, instead of commenting a separated version, I would directly do `50_000_000` if I ever needed to read big numbers quickly.

**Comment by sertdfyguhi** [comment]
i just wont

**Comment by SpeckyYT** [comment]
> i just wont

> Sounds like a you problem

**Comment by sertdfyguhi** [comment]
nah not really a problem, more like a blessing

**Comment by 7F6** [comment]
could you just do 5e+6? thats easy to read

**Comment by SpeckyYT** [comment]
> nah not really a problem, more like a blessing

Since you code in python, why aren't you blaming the pyhon devs for having this syntax?

**Comment by SpeckyYT** [comment]
> i dont blame you for making this pr wdym
> 

As already said, this is an optional syntax, nobody is forced to use it, therefore stop arguing about you not wanting to use it, since that's your choice, not ours.

**Comment by sertdfyguhi** [comment]
oki

**Comment by feverdreme** [comment]
> let foo = 5000000 //5,000,000

Yes we love redundant comments that clutter your code, which could be easily fixed by allowing ppl to underscore-separate numbers

**Comment by feverdreme** [comment]
Other countries also have different ways of separating their numbers. I think in some places of the world they do left to right instead of right to left, leading to things like 100,00 instead of 10,000. I think looking at the regex code this is correct so just something to keep in mind for international support

**Comment by feverdreme** [comment]
> could you just do 5e+6? thats easy to read

Would confused ppl that come from other langs since `5e+6` would create a float normally

**Pull request merged**
