### PR TITLE
Better gamescene

### PR DESCRIPTION
**Pull request by SpeckyYT**

### CODE REVIEW

**Comment by camila314** [comment]
is it still worth merging this or no

**Comment by SpeckyYT** [comment]
> is it still worth merging this or no

I guess it's worth, since it doesn't break when holding at the beginning of the level.

**Comment by camila314** [comment]
does it break existing code that uses gamescene

**Comment by SpeckyYT** [comment]
it's compatible with any previous code

**Comment by camila314** [comment]
gonna trust you on that

**Pull request merged**
