### PR TITLE
Added `sign` fn to std number lib

### PR DESCRIPTION
**Pull request by Rudxain**
Returns +1 if the input arg is positive, -1 if negative, +0 if +0, -0 if -0 (IDK if this lang supports -0, but I coded it like that to preserve data and be consistent with the IEEE-754 standard)

### CODE REVIEW

**Comment by krista-chan** [comment]
Cool

**Comment by krista-chan** [comment]
Please fix the errors detailed in the failed check

**Comment by Rudxain** [comment]
Sorry. I've added parentheses to see if it gets fixed. I tried searching for the SPWN syntax but didn't  find how to fix the parsing error. IDK why the compiler says there's a missing comma if I've read every char and it seems fine. I tested the parentheses expression in the playground and it works there

**Comment by krista-chan** [comment]
Please use the correct macro syntax.

**Comment by SpeckyYT** [comment]
apparently `(-1 if condition else +1)` has some parsing error, that's why it expects a `,`.

the only way I found to fix this is to do something like `(self) -> @number => self if self == 0 else (minus_one if self < 0 else 1),`

**Comment by Rudxain** [comment]
@SpeckyYT  I tested that expression in the playground and it doesn't work. I finally found the Ternary Expression documentation and the macro documentation but I still don't know how to fix the syntax error. I think I'll have to rewrite it as a block statement

**Comment by Rudxain** [comment]
@krista-chan  Now it's ready, tested multiple times in the playground 
@SpeckyYT  I realized the problem was the `else` clause of the ternary syntax. The `else` cannot handle unary operators (+, -, etc...)
@Spu7Nix  is this intentional or a bug?

**Pull request merged**
