### PR TITLE
Updated help.txt to include the thing that shows help.txt ig idk

### PR DESCRIPTION
**Pull request by smug-dev**
yes

### CODE REVIEW

**Comment by Reamuji** [comment]
actually there's a help subcommand

**Comment by Deltara3** [comment]
> actually there's a help subcommand but no help flags
> and any invalid flag will just be ignored

Iirc there is no help subcommand, any invalid subcommand (or just spwn) will up help

**Comment by Reamuji** [comment]
> 
> 
> > actually there's a help subcommand but no help flags
> > and any invalid flag will just be ignored
> 
> Iirc there is no help subcommand, any invalid subcommand (or just spwn) will up help

spwn help didn't throw unknwown subcommand

```
PS C:\Users\ASUS> spwn amogus
Unknown subcommand: amogus
Usage: spwn [subcommand] [flags]
```

```
PS C:\Users\ASUS> spwn help
Usage: spwn [subcommand] [flags]
```

**Comment by Reamuji** [comment]
help actually listed in src/main.rs line 56
```rs
match &args_iter.next() {
        Some(a) => {
            match a as &str {
                "help" => {
                    println!("{}", HELP);
                    Ok(())
                }
                "version" | "-v" | "--version" => {
                    println!("v{}", env!("CARGO_PKG_VERSION"));
                    Ok(())
                }
```

**Comment by camila314** [comment]
quite old

**Pull request closed without merging**
