### PR TITLE
Fixed 50% of the markdown lint errors on docs

### PR DESCRIPTION
**Pull request by SpeckyYT**

### CODE REVIEW

**Comment by zTags** [comment]
this is pogres

**Comment by krista-chan** [comment]
Fix 100%!!!!!!!!!!

**Comment by SpeckyYT** [comment]
> Fix 100%!!!!!!!!!!

I need to get better at Rust for that 💀

**Comment by krista-chan** [comment]
Fine

**Comment by zTags** [comment]
pogies

**Pull request merged**
