### PR TITLE
Add hex, binary, and octal literals

### PR DESCRIPTION
**Pull request by krista-chan**
This addition works at a compiler level, it always parses to a spwn `Number` during compile time

### CODE REVIEW

**Comment by SpeckyYT** [comment]
since we're here... what about octal 😳

**Comment by krista-chan** [comment]
> since we're here... what about octal 😳

Absolutely

**Comment by zTags** [comment]
what about (base65536)[https://github.com/qntm/base65536]

**Comment by zTags** [comment]
i know how to hyperlink dw

**Pull request merged**
