### PR TITLE
Added frame() and frames() (and removed "on_triggered"s)

### PR DESCRIPTION
**Pull request by SpeckyYT**
currently, `frames(10)` is not functional cause of an optimization bug (or probably cause I did r/badcode, idk)

### CODE REVIEW

**Comment by krista-chan** [comment]
Resolve?

**Comment by SpeckyYT** [comment]
> Resolve?

image

**Comment by krista-chan** [comment]
Amazing

**Comment by krista-chan** [comment]
SPECKYYY >:C

**Comment by SpeckyYT** [comment]
if this action compiles correctly, you can merge

**Pull request merged**
