### PR TITLE
dye module and escape characters yet again

### PR DESCRIPTION
**Pull request by DexterHill0**
very important content must merge!!!!!!!!!!!!

### CODE REVIEW

**Comment by krista-chan** [comment]
Do we need this in the stdlib?

**Comment by DexterHill0** [comment]
don't _need_ it but many many people do want it
its not going to go unused at least

**Comment by krista-chan** [comment]
I think that this should be kept as an external library, does anyone else agree?

**Comment by DexterHill0** [comment]
sad thats what was said last time but ig its fair
i still wanna at least have the escape characters added to spwn so ill make a new pr with them tommorrow but ill leave out dye and make in an external lib

**Comment by krista-chan** [comment]
Moving to the escapes, what's the purpose of [this](https://github.com/Spu7Nix/SPWN-language/pull/199/commits/f4e13ffa1622055ed3d8f7ed4134355c68413eec#diff-e5015daba7e3219b074887af2455a5f4b9540566dbbe4d7989cf6aea8fc27c20R1833) escape (`\b`)?

**Comment by DexterHill0** [comment]
`\b` is backspace it deletes the previous character
i just picked out some extra escape characters to add and out of all of them `\b` and `\u` were the most useful

**Comment by krista-chan** [comment]
What's useful about a backspace char in any string literal ever (although I do get `\u`)

**Comment by DexterHill0** [comment]
couldnt give an example but of all the escape chars
- `\'` -> already in spwn
- `\"` -> already in spwn
- `\\` -> already in spwn
- `\n` -> already in spwn
- `\r` -> already in spwn
- `\t` -> already in spwn
- `\f` -> completely useless
- `\v`-> completely useless
- `\0`-> completely useless
- `\u` -> veru useful
- `\b` -> idk might be useful at some point

**Comment by krista-chan** [comment]
`\b` seems useless in all practical situations

**Comment by feverdreme** [comment]
woah woah woah `\0` can be useful

**Comment by DexterHill0** [comment]
it can but not in the case of spwn
I cant think of a time ive ever added a null character into a string that wasnt in C

**Comment by krista-chan** [comment]
spwn/c ffi pgoggors?

**Pull request closed without merging**
