### PR TITLE
string.spwn add more escapes

### PR DESCRIPTION
**Pull request by psbpsbp**

### CODE REVIEW

**Comment by SpeckyYT** [comment]
spwn doesn't even have `'\a','\b','\v','\e'`

did you even test it? it should error while loading the std

**Comment by zTags** [comment]
you do keep trying i rate that

**Comment by psbpsbp** [comment]
> spwn doesn't even have `'\a','\b','\v','\e'`
> 
> did you even test it? it should error while loading the std

thats the thing they need to be aded

**Comment by SpeckyYT** [comment]
> > spwn doesn't even have `'\a','\b','\v','\e'`
> > did you even test it? it should error while loading the std
> 
> thats the thing they need to be aded

then you should add them to the built-ins instead of ""virtually adding them""

**Comment by psbpsbp** [comment]
> > > spwn doesn't even have `'\a','\b','\v','\e'`
> > > did you even test it? it should error while loading the std
> > 
> > 
> > thats the thing they need to be aded
> 
> then you should add them to the built-ins instead of ""virtually adding them""

i didn't know that was there just delete this one

**Comment by krista-chan** [comment]
Can you stop making prs

**Pull request closed without merging**
