### PR TITLE
Add Android support

### PR DESCRIPTION
**Pull request by Deltara3**
android support is cool

### CODE REVIEW

**Comment by Spu7Nix** [comment]
I think this might confuse a certain type of person. Is there no way to make it easier to install for android users?

**Comment by Deltara3** [comment]
> I think this might confuse a certain type of person. Is there no way to make it easier to install for android users?

We could, we would just need multiple packages for each architecture, armv7, armv8, armv9, etc. Root would still be required though.

**Comment by Spu7Nix** [comment]
maybe add a warning tho

**Comment by Deltara3** [comment]
true true ill do that real quick

**Comment by zTags** [comment]
this is cool

**Comment by sertdfyguhi** [comment]
how

**Comment by sertdfyguhi** [comment]
oh i see

**Comment by Deltara3** [comment]
> oh i see

It's fairly simple to do, but I figured because it was working, why don't I submit a pr?

**Comment by sertdfyguhi** [comment]
deltara

**Comment by Deltara3** [comment]
> deltara

yeah yo what up

**Comment by sertdfyguhi** [comment]
what browser do you use (name, version) and what search engine do you use?

**Comment by Deltara3** [comment]
what kind of question is that

**Comment by sertdfyguhi** [comment]
answer it

**Comment by Steviegt6** [comment]
> 
> 
> answer it

You okay my guy?

**Comment by sertdfyguhi** [comment]
yes im very well

**Pull request merged**
