### PR TITLE
Add new string flag 'u'

### PR DESCRIPTION
**Pull request by krista-chan**
## This flag removes newlines from the start and end of strings:

```rs
foo = u"
foo
bar
baz
"

$.print(foo)
```
Outputs:
```
foo
bar
baz
```

### CODE REVIEW

**Comment by Deltara3** [comment]
String flag similar to Python's `f"{var}"` when?

**Comment by SpeckyYT** [comment]
I wonder what about a way to extend the `c"h"` syntax at runtime.
```rs
@string::flags["t"] = string => string.trim()
```

**Comment by Spu7Nix** [comment]
> I wonder what about a way to extend the `c"h"` syntax at runtime.
> ```rs
> @string::flags["t"] = string => string.trim()
> 
> t"    hello guys     "
> ```

why tho, `"hello guys".t()` is fine

**Comment by DexterHill0** [comment]
thats called a macro

**Comment by zTags** [comment]
```rs
@string::add_flag("yourmomfat", () /* -> @string */ {
    // do funky shit here
    return "https://www.youtube.com/watch?v=xm3YgoEiEDc"
 });
```

**Comment by SpeckyYT** [comment]
string flags aren't longer than 1 character

**Comment by zTags** [comment]
```rs
@string::add_flag(" ", () /* -> @string */ {
    // do funky shit here
    return "https://www.youtube.com/watch?v=xm3YgoEiEDc";
 });
```
dw i gotchu

**Comment by krista-chan** [comment]
no.

**Comment by zTags** [comment]
wdym fuck yeah

**Comment by krista-chan** [comment]
# Notes about u flag syntax (important!!!)

## Example usage

```rs
u" // first line is skipped (do not write here)
    foo
        bar
    baz
"
```
Remaining lines will be shortened by the minimum amount of indentation only if there are enough spaces in the first place (described by the line below or linked [here](https://github.com/Spu7Nix/SPWN-language/pull/183/commits/3085cd5d0e14ca955aad59ae1dc9aca1ccc632af#diff-e5015daba7e3219b074887af2455a5f4b9540566dbbe4d7989cf6aea8fc27c20R1895))
```rs
if line.chars().take(min_indent).all(|c| c == ' ') { ... }
//                   ^^^^^^^^^^-----------Get min_indent amount of characters
//                               ^^^------Are they all spaces? (if yes: remove min_indent amount of chars. if no: do nothing to the line)
```

**Comment by Spu7Nix** [comment]
This should probably throw an error if the first char is not a newline, having the first like be treated as a comment is kinda not good

**Comment by zTags** [comment]
what if you wanna use `$.readfile()` and wanna make sure there are no spaces

**Comment by SpeckyYT** [comment]
> what if you wanna use `$.readfile()` and wanna make sure there are no spaces

`$.readfile().replace(' ','')`

**Comment by zTags** [comment]
fair enough

**Comment by SpeckyYT** [comment]
```rs
string = u"


    hello guys
        this is the 

            sussy impostor
                OWO


"
```
1) it should ignore lines that don't contain non-space characters for unindent
2) it should remove the empty lines at the start and on the end (maybe still keep the `\n` on the OWO)

**Comment by Spu7Nix** [comment]
It should still keep empty lines inside the string though

**Comment by Spu7Nix** [comment]
wait no i misunderstood

**Pull request merged**
