### PR TITLE
Rewrited @path

### PR DESCRIPTION
**Pull request by SpeckyYT**
Rewrote @path errors to something more epic

### CODE REVIEW

**Comment by krista-chan** [comment]
Won't merge yet, need to check cross platform behaviour as fs can be inconsistent across OSes (should have done this for initial `@path` pr too)

**Comment by SpeckyYT** [comment]
Input path is always normalized and then a formatted version is sent to the FS, therefore except the `~/` problem, I don't really know what other problems there might be.
If anyone finds anything, let me know.

**Comment by zTags** [comment]
what's the `~/` problem

**Comment by SpeckyYT** [comment]
> what's the `~/` problem

`~/../` should give `/` if you're on root or main account, else it should give `/home/`

**Comment by zTags** [comment]
you can technically fix this by using the `$HOME` environment variable if you have access to that

**Comment by SpeckyYT** [comment]
My main question is... would anyone care if the FS utility isn't perfect? It's a programming language made for compiling to geometry dash triggers, already the current system is more advanced then what it's needed.

**Comment by zTags** [comment]
truee

**Comment by zTags** [comment]
but spwn needs environment variables what if someone wants to use discord.spwn

**Comment by krista-chan** [comment]
> My main question is... would anyone care if the FS utility isn't perfect? It's a programming language made for compiling to geometry dash triggers, already the current system is more advanced then what it's needed.

If you're going to have paths in any language, do them right.

**Pull request merged**
