### PR TITLE
Add base64 string flag and expanded string flags

### PR DESCRIPTION
**Pull request by SpeckyYT**
# why?

because
```mermaid
sequenceDiagram
  participant Specky
  participant SPWN
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  Specky->>SPWN: PR
  SPWN->>Specky: gets banned
```

### CODE REVIEW

**Comment by krista-chan** [comment]
https://canary.discord.com/channels/791323294301290546/791323294796087308/943263734246297670

**Comment by SpeckyYT** [comment]
ok, turned the string flag char into a string, and now string flags are infinitely and easily expandable 😎😎😎😎😎😎😎😎😎

**Comment by zTags** [comment]
moment

**Comment by krista-chan** [comment]
Semantically only allow flags to be 1-2 `int`s or 1 `char`:
```_
64"foo"
^^ radix

b"bar", r"baz"
```
strings can only take this form, do not mix chars and ints in a flag name.

**Comment by SpeckyYT** [comment]
> Semantically only allow flags to be 1-2 `int`s or 1 `char`:
> ```_
> 64"foo"
> ^^ radix
> 
> b"bar", r"baz"
> ```
> strings can only take this form, do not mix chars and ints in a flag name.

idk, you wrote `radix""` on discord so I made sure that it could be possible

**Comment by krista-chan** [comment]
I'm fine with the regex, just change `bxx` to just `xx` (eg b64 -> 64)
Also, `radix""` was referring to literal numbers that don't have any chars

**Comment by SpeckyYT** [comment]
done 👌

**Comment by krista-chan** [comment]
Looks good, thank you

**Pull request merged**
