### PR TITLE
2022 :scream:

### PR DESCRIPTION
**Pull request by sertdfyguhi**
I'm blocking anyone with flag "🇺🇦" in their name or bio, the reason is because I feel like people are giving to much attention to this when Dreamsexuals have been struggling more for months, dreamsexuality is more important then this Ukraine thing, put "💚🖤🤍" instead.

### CODE REVIEW

**Review by SpeckyYT — APPROVED** [review]
not based

**Comment by sertdfyguhi** [comment]
bro its 27th of marhc

**Comment by sertdfyguhi** [comment]
Discovering my Dreamsexuality

 Okay... I need everyone's attention. The following is an important announcement regarding my journey discovering my sēxuality... Before discovering Dream's YouTube channel, I was always unsure of who I was. But one day, while browsing YouTube, I came across one of his videos. It was a manhunt. I watched it, and I felt something I had never felt before. Although it is extremely difficult to put into words, I felt a connection with him, as if I knew him in a previous life. This was when I realized there was a possibility that I could be dreamsēxual! For the next year, every morning I would get up and check my phone to watch his manhunts. They brought me so much joy... Soon enough, my entire room was decorated with everything Dream-themed. I threw out my whole wardrobe and was left with only my Dream merchandise. My favorite Dream hoodie would accompany me to school every day; I was bullied for wearing it. But that didn't faze me; I had Dream! He was my best friend... If he were at school with me, I knew he would have my back. I am so madly in love with him it is unimaginable. He is my hero, my life, my lover, my antidote. DREAM has cured my depression, my anxiety, and my chronic illness. I hope this message will open your eyes to the infinite possibilities that you may never have thought of.

**Review by SpeckyYT — CHANGES_REQUESTED** [review]
basedn't

**Review by splatterxl — COMMENTED** [review]
-1

**Pull request merged**
