### PR TITLE
Fix Arch path, for real this time.

### PR DESCRIPTION
**Pull request by Deltara3**
In addition to the Arch path fix, some minor capitalization errors that caught my eyes were fixed as well.

### CODE REVIEW

**Comment by Deltara3** [comment]
As of the new v0.6 package adding path manually is no longer required, so I'll close this.

**Comment by CarFanatic23** [comment]
19 dollar fortnite card

**Comment by FlowVix** [comment]
19 dollar fortnite card

**Comment by Deltara3** [comment]
19 dollar fortnite card

**Comment by feverdreme** [comment]
19 dollar fortnite card

**Comment by DorZ23** [comment]
19 dollar fortnite card

**Pull request closed without merging**
