### PR TITLE
Added more useful array methods

### PR DESCRIPTION
**Pull request by SpeckyYT**
me when
```rs
let array = [5, 3, 5, 2, 1 ]

if array.center() > array.pick() {
  $.print(array.center())
} else {
  $.print(array.shuffle.partition(v => v > 2)[0].most())
}
```

### CODE REVIEW

**Comment by camila314** [comment]
middle vs center? and also what happens if there's an even number

**Comment by SpeckyYT** [comment]
> middle vs center? 

I prefer `center`

> also what happens if there's an even number

it takes the first one of the two center ones, you can also do `array.center(true)` to take second one.

```rs
arr = [1,2,3,4]

arr.center() // 2
arr.center(true) // 3

arr = [1,2,3]

arr.center() // 2
arr.center(true) // 2
```

also I'll fix the conflicts later

**Comment by feverdreme** [comment]
I like middle better

**Comment by SpeckyYT** [comment]
fixed conflicts

**Pull request closed without merging**
