### PR TITLE
Create ASCII.spwn

### PR DESCRIPTION
**Pull request by psbpsbp**
Add's an ASCII function for doing @string to @number and @number to @string
(Why was it deleted?)

### CODE REVIEW

**Comment by zTags** [comment]
this is very dodgy

**Comment by SpeckyYT** [comment]
why do you give the literals `"\0", "^A", "Non breaking space"` instead of just returning the raw character?

**Comment by Rudxain** [comment]
`ASCII_list` is actually extended (8bit) ASCII, not true 7bit ASCII. And why did you choose 233 as limit? Seems kinda arbitrary to me. 7bit range is in the interval [0, 127], and printable chars are in a narrower interval I don't remember lol

**Comment by krista-chan** [comment]
#248

**Comment by psbpsbp** [comment]
> 

How?

**Comment by psbpsbp** [comment]
> why do you give the literals `"\0", "^A", "Non-breaking space"` instead of just returning the raw character?

How

**Comment by SpeckyYT** [comment]
as I already wrote in a different PR, you can do `"\u{D9E}"` to output a specific unicode character

**Pull request closed without merging**
