### PR TITLE
Fixed multiplying macros allocating 18 exabytes on negative numbers

### PR DESCRIPTION
**Pull request by SpeckyYT**
18 exabytes are kinda a lot as of today's standard

### CODE REVIEW

**Comment by zTags** [comment]
imagine not having 18 exabytes

**Comment by Spu7Nix** [comment]
Maybe this should error on negative numbers instead?

**Comment by SpeckyYT** [comment]
ok, I'll make that happen 😎

**Comment by zTags** [comment]
```rs
unreachable!();
```

**Comment by krista-chan** [comment]
gmd gg

**Pull request merged**
