### PR TITLE
add SOME bitwise operators (but not all) to RWRT

### PR DESCRIPTION
**Pull request by RealSput**
do not

### CODE REVIEW

**Comment by SpeckyYT** [comment]
rwrt2 literally started 5 minutes ago

**Comment by RealSput** [comment]
ok and?

**Comment by RealSput** [comment]
:>rofl

**Comment by RealSput** [comment]
> rwrt2 literally started 5 minutes ago

lmao whay

**Comment by RealSput** [comment]
bc idk how to differentiate between normal or and bitwise or 🤣

**Comment by GGodPL** [comment]
you mean the symbol for it?

**Comment by RealSput** [comment]
yse

**Comment by RealSput** [comment]
i mean the NOT symbol, specifically

**Comment by GGodPL** [comment]
bitwise NOT?

**Comment by RealSput** [comment]
yes, idk how to differentiate between normal NOT & bitwise NOT

**Comment by SpeckyYT** [comment]
this pr can be closed since those operations are already part of rwrt

**Pull request closed without merging**
