### PR TITLE
fix a vs an

### PR DESCRIPTION
**Pull request by CarFanatic23**
who did that

### CODE REVIEW

**Comment by zTags** [comment]
h the vowel amirite 🥶👌

**Comment by SpeckyYT** [comment]
"http" doesn't have any vowels from what I know 😂

**Comment by feverdreme** [comment]
dude that's not how grammar works. A vs An depends on the sounds rather than the actual spelling. Would you say "A honest man"? no. You would say "An honest man," even though "honest" begins with the letter h. The correct grammatical choice is to use "an"

**Comment by feverdreme** [comment]
Of course in standard english pronunciation it begins with the glottal stop, which is recognized as a consonant, but that doesn't really matter here, and the fact that the word begins with a vowel sound still stands

**Comment by sertdfyguhi** [comment]
"An HTTP request" doesn't sound correct to me

**Comment by feverdreme** [comment]
> Use "an" before a slient or unsounded "h." Because the "h" does not have any phonetic representation or audible sound, the sound that follows the article is a vowel; consequently, "an" is used.

Source: https://owl.purdue.edu/owl/general_writing/grammar/articles_a_versus_an.html

**Comment by zTags** [comment]
im pretty sure everyone says aich tee tee pee tho

**Comment by sertdfyguhi** [comment]
^^^^^^^^^^

**Comment by feverdreme** [comment]
"An HTTP request" sounds more natural to me, and it's grammatically correct

**Comment by sertdfyguhi** [comment]
yeah well ig but you didnt need to change it because both are correct

**Comment by feverdreme** [comment]
But its _not_. "An HTTP Request" is the only correct version

**Comment by feverdreme** [comment]
> The deciding factor for which of these words should be used is the sound that begins the word which follows these indefinite articles, rather than the letter which does. And there are scads of words in English that begin with a vowel, but which are initially voiced with a consonant sound (and vice versa).

Source: Merriam-Webster https://www.merriam-webster.com/words-at-play/is-it-a-or-an

**Comment by sertdfyguhi** [comment]
doesnt say that 'a' is incorrect

**Comment by feverdreme** [comment]
It says the deciding factor

**Comment by sertdfyguhi** [comment]
oops didnt see that

**Comment by feverdreme** [comment]
> The rule is: Use an before a word beginning with a vowel sound (not letter). It doesn’t matter how the word is spelled. It just matters how it is pronounced. Use a before a word with a consonant sound as well as y and w sounds. Which means it is not unusual to find a before a word starting with a vowel or an before a word starting with a consonant.

Source: https://www.thesaurus.com/e/grammar/a-vs-an/

**Comment by sertdfyguhi** [comment]
but `a` sounds way better than `an`

**Comment by feverdreme** [comment]
If course how nice things sound is all up to personal preference and is subjective for the most part, but nonetheless there are people that think "an" sounds better, and the fact that its grammatically correct should be reason enough to make the change in the official docs

**Comment by sertdfyguhi** [comment]
i am not native speaker of english but i disagree

**Comment by sertdfyguhi** [comment]
also english is stupid talk 中文

**Comment by sertdfyguhi** [comment]
that's why you should talk in chinese even more feverdreme

**Comment by feverdreme** [comment]
I'm not gonna pinyin my way through discord chat

**Comment by sertdfyguhi** [comment]
屌你

**Comment by feverdreme** [comment]
ok.

**Comment by sertdfyguhi** [comment]
不用拼音用速成或倉頡

**Comment by CarFanatic23** [comment]
use "a"
end of story

**Comment by FlowVix** [comment]
"an" is literally correct tho 😳

**Comment by feverdreme** [comment]
^^^

**Comment by CarFanatic23** [comment]
and so is "a"

**Comment by feverdreme** [comment]
No it isn't.

**Comment by Spu7Nix** [comment]
How would you even pronounce "a HTTP request"

**Pull request closed without merging**
