### PR TITLE
Added "@array::join"

### PR DESCRIPTION
**Pull request by SpeckyYT**
Why wasn't it added before?

### CODE REVIEW

**Comment by FlowVix** [comment]
cant the implementation just do `return joiner.join(self)` 🇲🇬

**Comment by SpeckyYT** [comment]
then what about the implementation for `@string::join` just being `return array.join(self)`

**Comment by SpeckyYT** [comment]
tbh, `array.join(string)` makes more sense than `string.join(array)`, so what about replacing the one in the string?

**Comment by FlowVix** [comment]
we can have both tbh

**Comment by SpeckyYT** [comment]
smartest conversation I ever hard

**Pull request merged**
