### PR TITLE
Added a simple inclusive range (..=) implementation

### PR DESCRIPTION
**Pull request by SpeckyYT**
idk if I did a decent job

### CODE REVIEW

**Comment by zTags** [comment]
if GitHub actions checks success on main you did a good job

**Comment by krista-chan** [comment]
fix `0..=0` => `0..1`

**Comment by zTags** [comment]
ok but why would you do that

**Comment by krista-chan** [comment]
it's a bug that produces unexpected behavior

**Comment by SpeckyYT** [comment]
> fix `0..=0` => `0..1`

that..... works already (?)

**Comment by zTags** [comment]
i was talking about why you'd wanna `0..=0` you have `[]`

**Comment by krista-chan** [comment]
`0..=0` _should_ resolve to `0..0` because it's a range from `0` to `0`, it's empty and thus should have no size.

**Comment by SpeckyYT** [comment]
`0..=0` results into `0..1`, which makes sense, since the end (`0`) is inclusive

**Comment by zTags** [comment]
shouldnt `0..=0` be `[0,0]`

**Comment by krista-chan** [comment]
Just SPWN things

**Comment by PrincessRavy** [comment]
> `0..=0` results into `0..1`, which makes sense, since the end (`0`) is inclusive
> 
> ```rust
> for i in 0..=0 {
>   $.print(i) // 0
> }
> ```

so, [0] includes 1? I don't understand how that makes sense

does that mean 0..=1 includes 2?

**Comment by SpeckyYT** [comment]
> does that mean 0..=1 includes 2?

obviously, `[0,1]`

**Comment by PrincessRavy** [comment]
> > does that mean 0..=1 includes 2?
> 
> obviously, i.e. `[0,1]`

that does not mean it includes 2, given 2 is not in [0,1] but I generally agree with your point now; 0..=0 should be [0], because inclusive means it _includes_ 0.

**Comment by SpeckyYT** [comment]
> so, [0] includes 1?

the usage of `includes` is extremely confusing in this context. I can't see the 1 in `[0]` tbh

**Comment by krista-chan** [comment]
haha im just dumb, inclusive range `0..=0` should in fact include `0` !!!

**Comment by zTags** [comment]
good job

**Comment by SpeckyYT** [comment]
```rs
0..=3 => [0,1,2,3] length: 4
0..=2 => [0,1,2] length: 3
0..=1 => [0,1] length: 2
0..=0 => [0] length: 1
```
does this not make sense to you all?

**Comment by SpeckyYT** [comment]
> haha im just dumb, inclusive range `0..=0` should in fact include `0` !!!

<bruh emoji>

**Comment by zTags** [comment]
🗿

**Pull request merged**
