### PR TITLE
array improvements

### PR DESCRIPTION
**Pull request by feverdreme**
- Added `copy` member method which returns a shallow copy of the array
- Changed `sort` method to sort in place
- Made `sorted` method to return a sorted array
- `sort` is now implemented with quicksort, which runs in O(nlogn) time, while previous ran in O(n^2)
- Added feature to sort with a heuristic

### CODE REVIEW

**Comment by feverdreme** [comment]
final PR update i swear

**Comment by sertdfyguhi** [comment]
3rd pr

**Comment by Spu7Nix** [comment]
The `copy` is unnecessary, SPWN is supposed to automatically clone arrays. Otherwise awesome pr!

**Comment by feverdreme** [comment]
do you want me to remove the `copy` function? The only reason I included that was because internals, and was worried if I just did ```spwn
let copy = self
``` then it would assign by reference rather than my value

**Comment by Spu7Nix** [comment]
Yea, you can remove it. It's not needed :)

**Pull request merged**
