### PR TITLE
Updated README with AUR package info

### PR DESCRIPTION
**Pull request by feverdreme**
Included the option to install SPWN from AUR building from source through this [package](https://aur.archlinux.org/packages/spwn)

### CODE REVIEW

**Comment by feverdreme** [comment]
checks failed to being with not my problem

**Comment by feverdreme** [comment]
merge this

**Comment by feverdreme** [comment]
you wont

**Comment by SpeckyYT** [comment]
consider the following: rwrt

**Comment by feverdreme** [comment]
consider the following: mrg

**Pull request closed without merging**
