### PR TITLE
Unfucked 99.9% of array methods

### PR DESCRIPTION
**Pull request by SpeckyYT**
aromagus

### CODE REVIEW

**Comment by feverdreme** [comment]
lmao shadowing go brrrrrrrrr

**Comment by SpeckyYT** [comment]
wait wha

**Comment by feverdreme** [comment]
most of these bugs are bc v0.0.7 removed shadowing

**Comment by SpeckyYT** [comment]
actually no, someone confused `@array::remove` with `@array::pop`

**Pull request merged**
