### PR TITLE
Removed inf and NaN + fixed specky dumb

### PR DESCRIPTION
**Pull request by kr8gz**

### CODE REVIEW

**Comment by SpeckyYT** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by itsmebombie** [comment]
🤣😂😂🤣😂🤣😂 heheheha

**Comment by kr8gz** [comment]
Fix krista stupid


😭😭😭😭😭😭icant fix srkits a stupid

its ==0.0

**Comment by itsmebombie** [comment]
is nan just 0 and inf max int number 😂🤣🤣😂🤣😂🤣😂

**Comment by itsmebombie** [comment]
(i am s

**Comment by krista-chan** [comment]
inf is supposed to be inf

**Comment by itsmebombie** [comment]
meh inf can stay but why nan when you can just error

**Comment by kr8gz** [comment]
when did you ever need inf in spwn

**Pull request merged**
