### PR TITLE
Added @log type

### PR DESCRIPTION
**Pull request by SpeckyYT**
90%* of the code in the future will be @log's 

\*unverified statistics

also happy easter 🐰🥚

### CODE REVIEW

**Comment by zTags** [comment]
🪵🪵🪵

**Comment by SpeckyYT** [comment]
I forgor to add docs 💀💀💀

**Comment by zTags** [comment]
that is cringe.

**Comment by Fl1pNatic** [comment]
that is cringe

**Comment by krista-chan** [comment]
Do we need this in the stdlib?

**Comment by SpeckyYT** [comment]
> Do we need this in the stdlib?

Sput said it would be useful, and it makes timing stuff easier.

**Pull request merged**
